---

platform: linux

image_resource:
  type: docker-image
  #source: {repository: python}
  source:
    repository: hello-world

inputs:
- name: concourse_test_repo

run:
  path: concourse_test_repo/scripts/test_bash.sh
