---

platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}
  #source: {repository: python}

inputs:
- name: concourse_test_repo

run:
  path: concourse_test_repo/scripts/test_bash.sh
