resources:
- name: concourse_test_repo
  type: git
  source:
    uri: https://github.com/ctinati/concourse_test
    branch: master

jobs:
- name: test-pipeline
  plan:
  - get: concourse_test_repo
    trigger: true
  - task: test_python
    file: concourse_test_repo/tasks/test_python.yml
  - task: test_bash
    file: concourse_test_repo/tasks/test_bash.yml
